# Generated by Django 5.2.1 on 2026-06-30 07:44

from django.db import migrations, models


def seed_tags(apps, schema_editor):
    Tag = apps.get_model('news', 'Tag')
    tags = [
        ('art', 'Art', 'Arte'),
        ('museum', 'Museum', 'Museo'),
        ('turin', 'Turin', 'Torino'),
        ('technology', 'Technology', 'Tecnologia'),
        ('events', 'Events', 'Eventi'),
        ('culture', 'Culture', 'Cultura'),
    ]
    for name, name_en, name_it in tags:
        Tag.objects.get_or_create(
            name=name,
            defaults={
                'name_en': name_en,
                'name_it': name_it,
            },
        )


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model('news', 'Tag')
    Tag.objects.filter(
        name__in=[
            'art',
            'museum',
            'turin',
            'technology',
            'events',
            'culture',
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_body_news_body_en_news_body_it_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=80, null=True, unique=True, verbose_name='name')),
                ('name_it', models.CharField(max_length=80, null=True, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag', verbose_name='tags'),
        ),
        migrations.RunPython(seed_tags, unseed_tags),
    ]
