# Generated by Django 5.2.1 on 2026-06-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_tag_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
    ]
